#!/usr/bin/env bash
# Install nginx on web-01 server

# Update the package list
sudo apt-get update

# Install Nginx
sudo apt-get -y install nginx

# Configure Nginx to listen on port 80
sudo sed -i 's/80 default_server/80/g' /etc/nginx/sites-available/default

# Create a page with "Hello World!" message
echo "Hello World!" | sudo tee /var/www/html/index.html

# Restart Nginx
sudo service nginx start
