#!/usr/bin/env bash
# Installs and configures Nginx on an Ubuntu server to serve "Hello World!" on port 80

apt-get update -y
apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.html
service nginx start
