#!/usr/bin/env bash
# This script tells a fictional story based on /etc/passwd

myfile="/etc/passwd"
while IFS=':' read -r username x userid groupid info homepath shell; do
    echo "The user ${username} is part of the ${groupid} gang, lives in ${homepath} and rides ${shell}. ${userid}'s place is protected by the passcode x, more info about the user here: ${info}"
done < /etc/passwd
